### ISSUE TITLE
Button "pay" should not be available if no account are available

### ISSUE THREAD

**Issue by vaab** [Lokavaluto/lokavaluto-web-application#21]
In the store, the assumption that `.getAccounts()` will always give a result is wrong. The cyclos account can be deactivated, or no account has been yet set up. We should provide a sane page when no information can be displayed.

(see all mentions of `accounts[0]` in `lokapi.ts`)

**Comment by seegwen** [comment]
Should be fixed in PR #24

**Comment by vaab** [comment]
I've re-oriented a little this issue, as it was unclear, and part of the code is now stronger, but we are still not doing this right:

Pay button and process (with modals) is available even if we don't have an available userAccount.

**Comment by seegwen** [comment]
Should be fixed in PR #52
